name: CI

on:
  push:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK v6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: install net6-macos and cake and build
        run: |
          dotnet tool install cake.tool --global
          dotnet workload install macos
      #    dotnet cake
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Build app for release
        run: msbuild /t:restore,build